export const USER = {
  SET: 'USER_SET',
  UNSET: 'USER_UNSET'
};

export const SIGNUP = {
  REQUESTING: 'SIGNUP_REQUESTING',
  SUCCESS: 'SIGNUP_SUCCESS',
  ERROR: 'SIGNUP_ERROR'
};

export const LOGIN = {
  REQUESTING: 'LOGIN_REQUESTING',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR'
};
